hydra:
  run:
    dir: concat


img_size: 256
data_csv: "/home/gominegishi/data/kgl/pet/petfinder-pawpularity-score/train.csv"
batch_size: 150
backbone: "EfficientNet"
lr: 0.001
lr_decay_freq: 10
epoch: 100
gpu: [0]
